services:
  # PostgreSQL база данных
  db:
    image: postgres:16-alpine
    container_name: calendar_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI приложение
  web:
    build: .
    container_name: calendar_app
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:1234@db:5432/postgres
      - SECRET_KEY=${SECRET_KEY:-f019399da0f734278e1f52}
      - ENV=development
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: