name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh -p 2222 -o StrictHostKeyChecking=no azwsdq@localhost "cd /home/azwsdq/all/calendar && git pull --rebase origin master && docker compose up -d --build"